openapi: 3.0.1
info:
  title: Creditas API
  description: API for loan simulation and batch processing
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /simulate:
    post:
      tags:
        - Loan Simulation
      summary: Simulate loan
      description: Simulate a loan for a customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoanSimulationRequestDTO'
      responses:
        '200':
          description: Successful loan simulation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InstallmentPlanResponseDTO'
  /batch/simulate:
    post:
      tags:
        - Batch Loan Simulation
      summary: Simulate loans in batch
      description: Simulate multiple loans in a batch process
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/LoanSimulationRequestDTO'
      responses:
        '200':
          description: Batch simulation initiated
          content:
            application/json:
              schema:
                type: string
                format: uuid
  /batch/status/{batchId}:
    get:
      tags:
        - Batch Loan Simulation
      summary: Get batch status
      description: Get the status of a batch loan simulation
      parameters:
        - name: batchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Batch status retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BatchStatusResponseDTO'
components:
  schemas:
    LoanSimulationRequestDTO:
      type: object
      properties:
        customerName:
          type: string
        birthDate:
          type: string
          format: date
        loanValue:
          type: number
          format: double
        installments:
          type: integer
        customerEmail:
          type: string
          format: email
      required:
        - customerName
        - birthDate
        - loanValue
        - installments
        - customerEmail
    InstallmentPlanResponseDTO:
      type: object
      properties:
        quantidadeParcelas:
          type: string
        valorParcelas:
          type: string
        totalComJuros:
          type: string
    BatchStatusResponseDTO:
      type: object
      properties:
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        elapsedTime:
          type: string